name: remainder_manager_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.10
  sqflite: ^2.3.3
  path: ^1.9.0
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  permission_handler: ^11.3.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"

  image: assets/icon/app_icon.png
  image_dark: assets/icon/app_icon.png

  android_12:
    color: "#FFFFFF"
    color_dark: "#000000"
    icon_background_color: "#FFFFFF"


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  
flutter:
  assets:
    - assets/svgs/global_search.svg
    - assets/icon/app_icon.png
    - assets/icon/logo.png

  uses-material-design: true
